"""followers

Revision ID: 279cc751860a
Revises: 3ef63d7c32c0
Create Date: 2020-10-07 19:17:49.574488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279cc751860a'
down_revision = '3ef63d7c32c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
